
development:
  adapter: postgresql
  encoding: unicode
  database: bazis_dev_1
  pool: 5
  username: bazis
  password: test
  host: localhost
  port: 5433

#  host: 192.168.0.105
#  port: 5433


test:
  adapter: postgresql
  encoding: unicode
  database: bazis_test
  pool: 5
  username: bazis
  password: test
  host: localhost
  port: 5433


production:
  adapter: postgresql
  encoding: unicode
  database: bazis_dev_1
  pool: 5
  username: bazis
  password: test

  host: localhost
  port: 5433
